feat: remove metrika goals
gravity-ui/blog-constructor pull request #177
Opened 2024-02-15 10:59 UTC by niktverd

2024-02-16 14:11 UTC, NikitaCG commented
you need create PR in `next` brach

2024-03-01 12:21 UTC, NikitaCG approved these changes

2024-03-01 12:21 UTC, NikitaCG commented on package.json
> +    "@gravity-ui/page-constructor": "^4.51.2-alpha.0",
merge after page-constructor5

2024-03-05 08:06 UTC, NikitaCG requested changes

2024-03-05 08:06 UTC, NikitaCG commented on src/blocks/Meta/Meta.tsx
> +                    // metrikaGoals={metrikaGoals}
and this

2024-03-05 08:19 UTC, NikitaCG approved these changes

2024-03-05 08:26 UTC, niktverd commented on src/components/PostCard/PostCard.tsx
> +            // metrikaGoals={metrikaGoals}
sure

2024-03-05 08:33 UTC, merged