fix: select filter a11y
gravity-ui/blog-constructor pull request #201
Opened 2024-07-31 10:50 UTC by PahaN47

2024-07-31 12:33 UTC, Kyzyl-ool approved these changes

2024-07-31 13:05 UTC, NikitaCG approved these changes

2024-08-01 13:04 UTC, Kyzyl-ool approved these changes

2024-08-02 10:08 UTC, NikitaCG requested changes

2024-08-05 10:34 UTC, PahaN47 commented
Nothing seems to be broken. Including the overrides

2024-08-05 11:02 UTC, NikitaCG approved these changes

2024-08-08 15:33 UTC, merged