feat: remove user context
gravity-ui/blog-constructor pull request #35
Opened 2023-04-20 14:59 UTC by niktverd

2023-04-20 21:48 UTC, NikitaCG commented on package.json
> +  "publishConfig": {
we dont need it

2023-04-20 21:49 UTC, NikitaCG commented on src/constructor/BlogConstructorProvider.tsx
> -    user?: UserContextProps;
remove information about it from contexts readme

2023-04-20 21:51 UTC, NikitaCG requested changes
fix comments

2023-04-25 05:06 UTC, niktverd commented on package.json
> +  "publishConfig": {
ok

2023-04-25 07:50 UTC, merged